// Code generated by goctl. DO NOT EDIT.
package types

type SendPhoneVerificationCodeRequest struct {
	Phone      string `json:"phone"`
	DeviceInfo string `json:"device_info"`
	ClientInfo string `json:"client_info"`
}

type SendEmailVerificationCodeRequest struct {
	Email      string `json:"email"`
	DeviceInfo string `json:"device_info"`
	ClientInfo string `json:"client_info"`
}

type SendVerificationCodeResponse struct {
}

type LoginCommon struct {
	DeviceInfo         string `json:"device_info"`
	ClientInfo         string `json:"client_info"`
	RegistrationSource string `json:"registration_source"`
	RegistrationIp     string `json:"registration_ip"`
}

type PhoneVerifyCodeLoginRequest struct {
	Phone            string      `json:"phone"`
	VerificationCode string      `json:"verification_code"`
	LoginCommon      LoginCommon `json:"login_common"`
}

type EmailVerifyCodeLoginRequest struct {
	Email            string      `json:"email"`
	VerificationCode string      `json:"verification_code"`
	LoginCommon      LoginCommon `json:"login_common"`
}

type PhonePassLoginRequest struct {
	Phone       string      `json:"phone"`
	Password    string      `json:"password"`
	LoginCommon LoginCommon `json:"login_common"`
}

type EmailLoginRequest struct {
	Email       string      `json:"email"`
	Password    string      `json:"password"`
	LoginCommon LoginCommon `json:"login_common"`
}

type TTkIDLoginRequest struct {
	TTkId       string      `json:"ttk_id"`
	Password    string      `json:"password"`
	LoginCommon LoginCommon `json:"login_common"`
}

type GithubLoginRequest struct {
	Token       string      `json:"token"`
	LoginCommon LoginCommon `json:"login_common"`
}

type LoginResponse struct {
	Token        string `json:"token"`
	TokenExpires int64  `json:"token_expires"`
}

type PhoneRegisterRequest struct {
	NickName string `json:"nickname"`
	Phone    string `json:"Phone"`
	Password string `json:"password"`
}

type EmailRegisterRequest struct {
	NickName string `json:"nickname"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type RegisterResponse struct {
}

type RefreshTokenRequest struct {
	Token string `json:"token"`
}

type RefreshTokenResponse struct {
	RefToken string `json:"ref_token"`
}

type UserInfo struct {
	ID            int64  `json:"id"`
	TTkID         string `json:"ttk_id"`
	NickName      string `json:"nick_name"`
	Gender        int32  `json:"gender"`
	Birthdate     string `json:"birthdate"`
	AvatarPath    string `json:"avatar_path"`
	Bio           string `json:"bio"`
	Country       string `json:"country"`
	City          string `json:"city"`
	Email         string `json:"email"`
	Phone         string `json:"phone"`
	AccountStatus int32  `json:"account_status"`
}

type GetUserInfoByUidRequest struct {
	Uid int64 `form:"uid"`
}

type GetUserInfoByTTKIdRequest struct {
	TTKId int64 `form:"ttk_id"`
}

type GetUserInfoResponse struct {
	UserInfo UserInfo `json:"user_info"`
}

type GetUserSelf struct {
}

type GetUserSelfResponse struct {
	UserInfo UserInfo `json:"user_info"`
}
