// Code generated by goctl. DO NOT EDIT.
package types

type SendPhoneVerificationCodeRequest struct {
	Phone      string `json:"phone"`
	DeviceInfo string `json:"device_info"`
	ClientInfo string `json:"client_info"`
}

type SendEmailVerificationCodeRequest struct {
	Email      string `json:"email"`
	DeviceInfo string `json:"device_info"`
	ClientInfo string `json:"client_info"`
}

type SendVerificationCodeResponse struct {
}

type PhoneVerifyCodeLoginRequest struct {
	Phone            string `json:"phone"`
	VerificationCode string `json:"verification_code"`
	DeviceInfo       string `json:"device_info"`
	ClientInfo       string `json:"client_info"`
}

type EmailVerifyCodeLoginRequest struct {
	Email            string `json:"email"`
	VerificationCode string `json:"verification_code"`
	DeviceInfo       string `json:"device_info"`
	ClientInfo       string `json:"client_info"`
}

type PhonePassLoginRequest struct {
	Phone      string `json:"phone"`
	Password   string `json:"password"`
	DeviceInfo string `json:"device_info"`
	ClientInfo string `json:"client_info"`
}

type EmailLoginRequest struct {
	Email      string `json:"email"`
	Password   string `json:"password"`
	DeviceInfo string `json:"device_info"`
	ClientInfo string `json:"client_info"`
}

type TTkIDLoginRequest struct {
	TTkId      string `json:"ttk_id"`
	Password   string `json:"password"`
	DeviceInfo string `json:"device_info"`
	ClientInfo string `json:"client_info"`
}

type GithubLoginRequest struct {
	Token      string `json:"token"`
	DeviceInfo string `json:"device_info"`
	ClientInfo string `json:"client_info"`
}

type LoginResponse struct {
	Token        string `json:"token"`
	TokenExpires string `json:"token_expires"`
}

type PhoneRegisterRequest struct {
	NickName string `json:"nickname"`
	Phone    string `json:"Phone"`
	Password string `json:"password"`
}

type EmailRegisterRequest struct {
	NickName string `json:"nickname"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type RegisterResponse struct {
}

type RefreshTokenRequest struct {
	Token string `json:"token"`
}

type RefreshTokenResponse struct {
	RefToken string `json:"ref_token"`
}

type UserInfo struct {
	TTkId string `json:"ttk_id"`
}

type GetUserInfoByUidRequest struct {
	Uid int64 `form:"uid"`
}

type GetUserInfoByTTKIdRequest struct {
	TTKId int64 `form:"ttk_id"`
}

type GetUserInfoResponse struct {
	UserInfo UserInfo `json:"user_info"`
}
