// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package server

import (
	"context"

	"topview-ttk/internal/app/ttk-user/rpc/internal/logic/user"
	"topview-ttk/internal/app/ttk-user/rpc/internal/svc"
	"topview-ttk/internal/app/ttk-user/rpc/user"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) Ping(ctx context.Context, in *user.Request) (*user.Response, error) {
	l := userlogic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
