// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package server

import (
	"context"

	"topview-ttk/internal/app/ttk-user/rpc/internal/logic/ssoservice"
	"topview-ttk/internal/app/ttk-user/rpc/internal/svc"
	"topview-ttk/internal/app/ttk-user/rpc/user"
)

type SsoServiceServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedSsoServiceServer
}

func NewSsoServiceServer(svcCtx *svc.ServiceContext) *SsoServiceServer {
	return &SsoServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *SsoServiceServer) SendPhoneVerificationCode(ctx context.Context, in *user.SendPhoneVerificationCodeRequest) (*user.SendPhoneVerificationCodeResponse, error) {
	l := ssoservicelogic.NewSendPhoneVerificationCodeLogic(ctx, s.svcCtx)
	return l.SendPhoneVerificationCode(in)
}

func (s *SsoServiceServer) PhoneVerifyCodeLogin(ctx context.Context, in *user.PhoneVerifyCodeLoginRequest) (*user.PhoneVerifyCodeLoginResponse, error) {
	l := ssoservicelogic.NewPhoneVerifyCodeLoginLogic(ctx, s.svcCtx)
	return l.PhoneVerifyCodeLogin(in)
}

func (s *SsoServiceServer) SendEmailVerificationCode(ctx context.Context, in *user.SendEmailVerificationCodeRequest) (*user.SendEmailVerificationCodeResponse, error) {
	l := ssoservicelogic.NewSendEmailVerificationCodeLogic(ctx, s.svcCtx)
	return l.SendEmailVerificationCode(in)
}

func (s *SsoServiceServer) EmailVerifyCodeLogin(ctx context.Context, in *user.EmailVerifyCodeLoginRequest) (*user.EmailVerifyCodeLoginResponse, error) {
	l := ssoservicelogic.NewEmailVerifyCodeLoginLogic(ctx, s.svcCtx)
	return l.EmailVerifyCodeLogin(in)
}
