// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	sso "topview-ttk/internal/app/ttk-api/internal/handler/sso"
	user "topview-ttk/internal/app/ttk-api/internal/handler/user"
	"topview-ttk/internal/app/ttk-api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/sso/sendPhoneVerificationCode",
				Handler: sso.SendPhoneVerificationCodeHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/sso/sendEmailVerificationCode",
				Handler: sso.SendEmailVerificationCodeHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/sso/phoneVerifyCodeLogin",
				Handler: sso.PhoneVerifyCodeLoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/sso/emailVerifyCodeLogin",
				Handler: sso.EmailVerifyCodeLoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/sso/phonePassLogin",
				Handler: sso.PhonePassLoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/sso/emailPassLogin",
				Handler: sso.EmailPassLoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/sso/TTKIDPassLogin",
				Handler: sso.TtkidPassLoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/sso/GithubLogin",
				Handler: sso.GithubLoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/sso/PhoneRegister",
				Handler: sso.PhoneRegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/sso/EmailRegister",
				Handler: sso.EmailRegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/sso/RefreshToken",
				Handler: sso.RefreshTokenHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/user/info",
				Handler: user.GetUserInfoByUidHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/infoByTTKId",
				Handler: user.GetUserInfoByTTKIdHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1"),
	)
}
