// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	user "topview-ttk/internal/app/ttk-api/internal/handler/user"
	"topview-ttk/internal/app/ttk-api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/sso/sendPhoneVerificationCode",
				Handler: user.SendPhoneVerificationCodeHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/sso/sendEmailVerificationCode",
				Handler: user.SendEmailVerificationCodeHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/sso/phoneVerifyCodeLogin",
				Handler: user.PhoneVerifyCodeLoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/sso/emailVerifyCodeLogin",
				Handler: user.EmailVerifyCodeLoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/sso/phonePassLogin",
				Handler: user.PhonePassLoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/sso/emailOrTtkPassLogin",
				Handler: user.EmailOrTtkPassLoginHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1"),
	)
}
