datasource:
  ttk-user:
    username: root
    password: topview
    host: 10.21.23.117:31999
    dbname: ttk_user
    dsn: ${datasource.ttk-user.username}:${datasource.ttk-user.password}@tcp(${datasource.ttk-user.host})/${datasource.ttk-user.dbname}?charset=utf8&parseTime=True&loc=Local
    gorm:
      max-idle-connections: 10  # 最大空闲连接数
      max-open-connections: 100  # 最大打开连接数
      conn-max-lifetime: 8