// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package userservice

import (
	"context"

	"topview-ttk/internal/app/ttk-user/rpc/user"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	EmailPassLoginRequest            = user.EmailPassLoginRequest
	EmailRegisterRequest             = user.EmailRegisterRequest
	EmailVerifyCodeLoginRequest      = user.EmailVerifyCodeLoginRequest
	GetUserInfoByTTKIdRequest        = user.GetUserInfoByTTKIdRequest
	GetUserInfoByUidRequest          = user.GetUserInfoByUidRequest
	GetUserInfoResponse              = user.GetUserInfoResponse
	GitHubLoginRequest               = user.GitHubLoginRequest
	LoginCommon                      = user.LoginCommon
	LoginResponse                    = user.LoginResponse
	PhonePassLoginRequest            = user.PhonePassLoginRequest
	PhoneRegisterRequest             = user.PhoneRegisterRequest
	PhoneVerifyCodeLoginRequest      = user.PhoneVerifyCodeLoginRequest
	RefreshTokenRequest              = user.RefreshTokenRequest
	RefreshTokenResponse             = user.RefreshTokenResponse
	RegisterResponse                 = user.RegisterResponse
	SendEmailVerificationCodeRequest = user.SendEmailVerificationCodeRequest
	SendPhoneVerificationCodeRequest = user.SendPhoneVerificationCodeRequest
	SendVerificationCodeResponse     = user.SendVerificationCodeResponse
	TTKIdPassLoginRequest            = user.TTKIdPassLoginRequest
	UserInfo                         = user.UserInfo

	UserService interface {
		GetUserInfoByUid(ctx context.Context, in *GetUserInfoByUidRequest, opts ...grpc.CallOption) (*GetUserInfoResponse, error)
		GetUserInfoByTTKId(ctx context.Context, in *GetUserInfoByTTKIdRequest, opts ...grpc.CallOption) (*GetUserInfoResponse, error)
	}

	defaultUserService struct {
		cli zrpc.Client
	}
)

func NewUserService(cli zrpc.Client) UserService {
	return &defaultUserService{
		cli: cli,
	}
}

func (m *defaultUserService) GetUserInfoByUid(ctx context.Context, in *GetUserInfoByUidRequest, opts ...grpc.CallOption) (*GetUserInfoResponse, error) {
	client := user.NewUserServiceClient(m.cli.Conn())
	return client.GetUserInfoByUid(ctx, in, opts...)
}

func (m *defaultUserService) GetUserInfoByTTKId(ctx context.Context, in *GetUserInfoByTTKIdRequest, opts ...grpc.CallOption) (*GetUserInfoResponse, error) {
	client := user.NewUserServiceClient(m.cli.Conn())
	return client.GetUserInfoByTTKId(ctx, in, opts...)
}
