// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package server

import (
	"context"

	"topview-ttk/internal/app/ttk-user/rpc/internal/logic/userservice"
	"topview-ttk/internal/app/ttk-user/rpc/internal/svc"
	"topview-ttk/internal/app/ttk-user/rpc/user"
)

type UserServiceServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserServiceServer
}

func NewUserServiceServer(svcCtx *svc.ServiceContext) *UserServiceServer {
	return &UserServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServiceServer) Ping(ctx context.Context, in *user.Request) (*user.Response, error) {
	l := userservicelogic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
